# Set to true to add reviewers to pull requests
addReviewers: true
#
reviewers:
  - RKeyIT
  - ValeryiaPraslova

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 1

# Set to true to add assignees to pull requests
addAssignees: true

assignees:
  - author
