name: Auto Assign PR Creator

on:
  pull_request:
    types: [opened]

jobs:
  assign_author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR Author
        uses: TimonVS/auto-assign-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/auto-assign.yml
